baseURL = "https://docs.gibbonedu.org/"
languageCode = "en-gb"
DefaultContentLanguage = "en"

title = "Gibbon Documentation"
theme = "gibbon"
themesdir = "themes"
enableGitInfo = false

## Syntax Highlighting
pygmentsCodefences = true
pygmentsStyle = "manni"
pygmentsOptions = "startinline=true"

[params]
logo = "/images/gibbon-logo.png"
version = "v20.0.00"
ghRepo = "https://github.com/GibbonEdu/docs/"
newURL = "https://github.com/GibbonEdu/docs/new/master/content/"
editURL = "https://github.com/GibbonEdu/docs/edit/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
highlightStyle = "atom-one-dark"
themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title" | "weight"
pluralizelisttitles = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


## Top Menu Links

[[menu.links]]
name = "Home"
url = "https://gibbonedu.org"
weight = 10
identifier = "primary"

[[menu.links]]
name = "About"
url = "https://gibbonedu.org/about"
weight = 20

[[menu.links]]
name = "Features"
url = "https://gibbonedu.org/features"
weight = 30

[[menu.links]]
name = "Download"
url = "https://gibbonedu.org/download"
weight = 40

[[menu.links]]
name = "Extend"
url = "https://gibbonedu.org/extend"
weight = 50

[[menu.links]]
name = "Support"
url = "https://docs.gibbonedu.org"
weight = 60


## Sidebar Links

[[menu.shortcuts]]
pre = "<h5>Links</h5>"
name = "<i class='fa fa-fw fa-comments-o'></i> Support Forum"
url = "https://ask.gibbonedu.org"
weight = 20

[[menu.shortcuts]]

name = "<i class='fa fa-fw fa-github'></i> Gibbon on GitHub"
identifier = "ds"
url = "https://github.com/GibbonEdu/core/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Docs on GitHub"
url = "https://github.com/GibbonEdu/docs/"
weight = 40

## Related Content Settings

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80
# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true
# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "categories"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
